---
- name: Configure webserver with nginx but no TLS
  hosts: webservers
  become: True
  vars:
    - local_files_dir: ../files
    - local_templates_dir: ../templates
  tasks:
    - name: Install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: Copy over nginx config file
      copy: >
        src={{local_files_dir}}/nginx.conf
        dest=/etc/nginx/sites-available/default

    - name: Enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: Copy over index.html
      template: >
        src={{local_templates_dir}}/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: Restart nginx
      service: name=nginx state=restarted
